#!/bin/sh

# below only installed to show how to add Python packages into the container
# pip install --no-cache -r requirements.txt

python -u my_app.py --debug
#python -u my_set_app_03_20.py --debug
#python -u my_get_app_03_20.py --debug
#python -u my_get_app.py --debug
#./my_run
#python -u my_run --debug
#python -u 1my_get_app.py --debug
#python -u 2my_get_app.py --debug
#python -u time.py --debug
#python -u tiny_get_app.py --debug
#python -u my_get_app_11_30.py --debug
#python -u my_get_app10.py --debug
#python -u my_get_app11.py --debug
#python -u my_get_app12.py --debug

#python -u my_get_app_5_13.py --debug
#python -u my_get_app2.py --debug
#python -u my_get_app3.py --debug
#python -u my_get_app2.py --debug

#python -u my_set_app.py --debug

#python -u test.py --debug
#python -u client_kikis.py --debug

#python -u client_tx.py
#python -u client_longop.py --debug
#python -u client_aio.py
